/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

import app.AppContext;
import javax.swing.JOptionPane;
import model.Usuario;
import service.ServicoUsuario;

/**
 *
 * @author upo
 */
public class TelaEditarMeuPerfil extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaEditarMeuPerfil
     */
    public TelaEditarMeuPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        btAtualizarDados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pwfSenhaAntiga = new javax.swing.JPasswordField();
        pwfSenhaNova = new javax.swing.JPasswordField();
        pwfSenhaNovaConfirmar = new javax.swing.JPasswordField();

        setClosable(true);
        setTitle("Editar Meu Perfil");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Novo Nome de Usuário ");

        btAtualizarDados.setText("Atualizar Dados");
        btAtualizarDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAtualizarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarDadosActionPerformed(evt);
            }
        });

        jLabel2.setText("Senha Antiga");

        jLabel3.setText("Senha Nova");

        jLabel4.setText("Confirmar Senha Nova");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(pwfSenhaNova)
                    .addComponent(pwfSenhaAntiga)
                    .addComponent(pwfSenhaNovaConfirmar))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAtualizarDados)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pwfSenhaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pwfSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pwfSenhaNovaConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btAtualizarDados)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAtualizarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarDadosActionPerformed
        // TODO add your handling code here:
        ServicoUsuario servico = AppContext.getInstanceServicoUsuario();
        Usuario usuario = AppContext.getUsuarioLogado();
        
        String nome = txtNomeUsuario.getText();
        String senhaAntiga = new String(pwfSenhaAntiga.getPassword());
        String senhaNova = new String(pwfSenhaNova.getPassword());
        String senhaNovaConfirmar = new String(pwfSenhaNovaConfirmar.getPassword());
        
        if(!(nome.isEmpty() || senhaAntiga.isEmpty() || senhaNova.isEmpty() || senhaNovaConfirmar.isEmpty())){
            if (senhaAntiga.equals(usuario.getSenha())) {
                
                if(senhaNova.equals(senhaNovaConfirmar)){
                    
                    try{
                        servico.atualizarDados(usuario.getNomeUsuario(), senhaAntiga, nome, senhaNova);
                        JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!");
                        this.dispose();
                    }catch(IllegalArgumentException e){
                        JOptionPane.showMessageDialog(null, e.getMessage(),"Erro ao cadastrar",JOptionPane.ERROR_MESSAGE);
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "As senhas não coincidem!","Não foi possivel atualizar",JOptionPane.WARNING_MESSAGE);
                    limparCampos();
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "Senha Atual Incorreta!","Não foi possivel atualizar o seu perfil",JOptionPane.WARNING_MESSAGE);
                limparCampos();
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
    }//GEN-LAST:event_btAtualizarDadosActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
    
        ServicoUsuario servico = AppContext.getInstanceServicoUsuario();
        Usuario usuario = AppContext.getUsuarioLogado();
        
        txtNomeUsuario.setText(usuario.getNomeUsuario());
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void limparCampos(){
        Usuario usuario = AppContext.getUsuarioLogado();
        
        txtNomeUsuario.setText(usuario.getNomeUsuario());
        pwfSenhaAntiga.setText(null);
        pwfSenhaNova.setText(null);
        pwfSenhaNovaConfirmar.setText(null);
        
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizarDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pwfSenhaAntiga;
    private javax.swing.JPasswordField pwfSenhaNova;
    private javax.swing.JPasswordField pwfSenhaNovaConfirmar;
    private javax.swing.JTextField txtNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
