/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

import app.AppContext;
import java.util.Arrays;
import javax.swing.JOptionPane;
import model.TipoConta;
import model.Usuario;
import service.ServicoUsuario;

/**
 *
 * @author upo
 */
public class TelaCadastrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastrar
     */
    public TelaCadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        grupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        pwfSenha = new javax.swing.JPasswordField();
        pwfSenhaConfirmar = new javax.swing.JPasswordField();
        btLimparCampos = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        radioNormal = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        radioAdministrador = new javax.swing.JRadioButton();

        grupo.add(radioAdministrador);
        grupo.add(radioNormal);

        setClosable(true);
        setTitle("Cadastrar Usuários");
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(753, 517));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Nome do Usuário");

        jLabel2.setText("Senha");

        jLabel3.setText("Confirmar Senha");

        txtNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeUsuarioActionPerformed(evt);
            }
        });

        pwfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwfSenhaActionPerformed(evt);
            }
        });

        btLimparCampos.setText("Limpar");
        btLimparCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCamposActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        radioNormal.setText("Normal");
        radioNormal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setText("Tipo de Conta");

        radioAdministrador.setText("Administrador");
        radioAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeUsuario)
                    .addComponent(pwfSenha)
                    .addComponent(pwfSenhaConfirmar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioNormal)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btLimparCampos)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioAdministrador))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btCadastrar)
                                .addGap(0, 60, Short.MAX_VALUE)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pwfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(pwfSenhaConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(radioNormal)
                        .addComponent(radioAdministrador)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparCampos)
                    .addComponent(btCadastrar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        setBounds(0, 0, 629, 368);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeUsuarioActionPerformed

    private void pwfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwfSenhaActionPerformed

    private void btLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCamposActionPerformed
        // TODO add your handling code here:
        txtNomeUsuario.setText(null);
        pwfSenha.setText(null);
        pwfSenhaConfirmar.setText(null);
        
    }//GEN-LAST:event_btLimparCamposActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        if(verificarCampos()){
            String nome = txtNomeUsuario.getText();
            String senha = new String(pwfSenha.getPassword());
            TipoConta tipo = null;
            
            if(radioNormal.isSelected()){
                tipo = TipoConta.NORMAL;
            }
            
            if(radioAdministrador.isSelected()){
                tipo = TipoConta.ADMINISTRADOR;
            }
            
            ServicoUsuario servicoUsuario = AppContext.servicoUsuario;
            
            try{
                servicoUsuario.cadastrar(new Usuario(nome,senha,tipo));
                limparCampos();
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!","Sucesso",JOptionPane.INFORMATION_MESSAGE);
            }catch(IllegalArgumentException e){
                JOptionPane.showMessageDialog(null, e.getMessage(), "Erro ao cadastrar", JOptionPane.ERROR_MESSAGE);
                limparCampos();
            }
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
            // TODO add your handling code here:

            
    }//GEN-LAST:event_formInternalFrameActivated
    private boolean verificarCampos(){
        if(txtNomeUsuario.getText().trim().isEmpty() || pwfSenha.getPassword().length == 0 || pwfSenhaConfirmar.getPassword().length == 0
                || (!radioNormal.isSelected() && !radioAdministrador.isSelected())){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
            return false;
        }else{
            if(!Arrays.equals(pwfSenha.getPassword(), pwfSenhaConfirmar.getPassword())){
                JOptionPane.showMessageDialog(null, "As senhas não coincidem!","Não foi possivel cadastrar",JOptionPane.WARNING_MESSAGE);
                pwfSenha.setText(null);
                pwfSenhaConfirmar.setText(null);
                return false;
            }
        }
        
        return true;
    }
    
    private void limparCampos(){
        txtNomeUsuario.setText(null);
        pwfSenha.setText(null);
        pwfSenhaConfirmar.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimparCampos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pwfSenha;
    private javax.swing.JPasswordField pwfSenhaConfirmar;
    private javax.swing.JRadioButton radioAdministrador;
    private javax.swing.JRadioButton radioNormal;
    private javax.swing.JTextField txtNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
