/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;
import app.AppContext;
import javax.swing.JOptionPane;
import model.TipoConta;
import model.Usuario;
import service.ServicoUsuario;
import static ui.TelaPrincipal.desktop;
/**
 *
 * @author upo
 */
public class TelaEditarUsuario extends javax.swing.JInternalFrame {
    private final String NOME_DO_USUARIO;
    private ServicoUsuario servicoUsuario;
    private Usuario usuario;
    
    /**
     * Creates new form TelaEditarUsuario
     */
    public TelaEditarUsuario(String nomeDoUsario) {
        
        initComponents();
        
        
        this.NOME_DO_USUARIO = nomeDoUsario;
        desktop.add(this);
        servicoUsuario = AppContext.servicoUsuario;
        usuario = servicoUsuario.getUser(NOME_DO_USUARIO);
        lbNomeUsuarioAtual.setText(NOME_DO_USUARIO);
        comboTipoConta.setSelectedItem(usuario.getTipoConta().toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNomeUsuarioAtual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboTipoConta = new javax.swing.JComboBox<>();
        btAtualizarDados = new javax.swing.JButton();

        setClosable(true);
        setTitle("Atualizar os Dados da Conta");

        lbNomeUsuarioAtual.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lbNomeUsuarioAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNomeUsuarioAtual.setText("NOME");

        jLabel1.setText("Tipo de Conta");

        comboTipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NORMAL", "ADMINISTRADOR"}));
        comboTipoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoContaActionPerformed(evt);
            }
        });

        btAtualizarDados.setText("Atualizar Dados");
        btAtualizarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbNomeUsuarioAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btAtualizarDados)
                        .addGap(187, 187, 187))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbNomeUsuarioAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btAtualizarDados)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoContaActionPerformed

    private void btAtualizarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarDadosActionPerformed
        // TODO add your handling code here:
        String tipoContaAtual = usuario.getTipoConta().toString();
        if(tipoContaAtual.equalsIgnoreCase(comboTipoConta.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "Não fez nenhuma alteracao!");
        }else{
            
            int op = JOptionPane.showConfirmDialog(null, "Atualizar tipo de conta de " + NOME_DO_USUARIO + " para " + comboTipoConta.getSelectedItem().toString());
            if(op == JOptionPane.YES_OPTION){
                if(comboTipoConta.getSelectedItem().toString().equals("ADMINISTRADOR")){
                    servicoUsuario.atualizarTipoConta(NOME_DO_USUARIO, TipoConta.ADMINISTRADOR);
                }else{
                    servicoUsuario.atualizarTipoConta(NOME_DO_USUARIO, TipoConta.NORMAL);
                }
                JOptionPane.showMessageDialog(null, "Atualizado com Sucesso!");
            }
            
            this.dispose();
        }
    }//GEN-LAST:event_btAtualizarDadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizarDados;
    private javax.swing.JComboBox<String> comboTipoConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbNomeUsuarioAtual;
    // End of variables declaration//GEN-END:variables
}
